# Fixtures file hold the dependencies for spec helper

fixtures:
  forge_modules:   
    archive:
      repo: "puppet/archive"
      ref: "3.2.1"  
    apt:
      repo: "puppetlabs/apt"
      ref: "6.2.1"
    augeas_core:
      repo: "puppetlabs/augeas_core"
      ref: "1.0.3"  
    concat:
      repo: "puppetlabs/concat"
      ref: "5.2.0"
    postgresql:
      repo: "puppetlabs/postgresql"
      ref: "5.11.0"
    stdlib:
     repo: "puppetlabs/stdlib"
     ref: "5.1.0"
    tftp:
      repo: "puppetlabs/tftp"
      ref: "1.0.0"
    vcsrepo:
      repo: "puppetlabs/vcsrepo"
      ref: "2.4.0"    
    xinetd:
      repo: "puppetlabs/xinetd"
      ref: "3.1.0"  
      
  symlinks:
    razor: "#{source_dir}"
